### ISSUE TITLE
FileNotFoundError in tutorial.ipynb

### ISSUE THREAD

**Issue by hbsong-03** [MannLabs/structuremap#11]
I have pip installed structuremap and was running through the tutorials, but it will report bugs in the ANNONATE PTM DATA section. Is my installation not complete?

In: Annotate PTM data
     ptm_file_location = os.path.join("..","data","test_files","ptm_file.csv")
     ptm_file = pd.read_csv(ptm_file_location)

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Input In [21], in <cell line: 2>()
      1 ptm_file_location = os.path.join("..","data","test_files","ptm_file.csv")
----> 2 ptm_file = pd.read_csv(ptm_file_location)

File ~\anaconda3\envs\structuremap\lib\site-packages\pandas\util\_decorators.py:311, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    305 if len(args) > num_allow_args:
    306     warnings.warn(
    307         msg.format(arguments=arguments),
    308         FutureWarning,
    309         stacklevel=stacklevel,
    310     )
--> 311 return func(*args, **kwargs)

File ~\anaconda3\envs\structuremap\lib\site-packages\pandas\io\parsers\readers.py:680, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    665 kwds_defaults = _refine_defaults_read(
    666     dialect,
    667     delimiter,
   (...)
    676     defaults={"delimiter": ","},
    677 )
    678 kwds.update(kwds_defaults)
--> 680 return _read(filepath_or_buffer, kwds)

File ~\anaconda3\envs\structuremap\lib\site-packages\pandas\io\parsers\readers.py:575, in _read(filepath_or_buffer, kwds)
    572 _validate_names(kwds.get("names", None))
    574 # Create the parser.
--> 575 parser = TextFileReader(filepath_or_buffer, **kwds)
    577 if chunksize or iterator:
    578     return parser

File ~\anaconda3\envs\structuremap\lib\site-packages\pandas\io\parsers\readers.py:934, in TextFileReader.__init__(self, f, engine, **kwds)
    931     self.options["has_index_names"] = kwds["has_index_names"]
    933 self.handles: IOHandles | None = None
--> 934 self._engine = self._make_engine(f, self.engine)

File ~\anaconda3\envs\structuremap\lib\site-packages\pandas\io\parsers\readers.py:1218, in TextFileReader._make_engine(self, f, engine)
   1214     mode = "rb"
   1215 # error: No overload variant of "get_handle" matches argument types
   1216 # "Union[str, PathLike[str], ReadCsvBuffer[bytes], ReadCsvBuffer[str]]"
   1217 # , "str", "bool", "Any", "Any", "Any", "Any", "Any"
-> 1218 self.handles = get_handle(  # type: ignore[call-overload]
   1219     f,
   1220     mode,
   1221     encoding=self.options.get("encoding", None),
   1222     compression=self.options.get("compression", None),
   1223     memory_map=self.options.get("memory_map", False),
   1224     is_text=is_text,
   1225     errors=self.options.get("encoding_errors", "strict"),
   1226     storage_options=self.options.get("storage_options", None),
   1227 )
   1228 assert self.handles is not None
   1229 f = self.handles.handle

File ~\anaconda3\envs\structuremap\lib\site-packages\pandas\io\common.py:786, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    781 elif isinstance(handle, str):
    782     # Check whether the filename is to be opened in binary mode.
    783     # Binary mode does not support 'encoding' and 'newline'.
    784     if ioargs.encoding and "b" not in ioargs.mode:
    785         # Encoding
--> 786         handle = open(
    787             handle,
    788             ioargs.mode,
    789             encoding=ioargs.encoding,
    790             errors=errors,
    791             newline="",
    792         )
    793     else:
    794         # Binary mode
    795         handle = open(handle, ioargs.mode)

FileNotFoundError: [Errno 2] No such file or directory: '..\\data\\test_files\\ptm_file.csv'

**Comment by ibludau** [comment]
Sorry for not responding to this issue earlier - could you solve the issue by now? If you used the installer on windows, the data might not be included by default and a manual download of the test data might be necessary.
