### ISSUE TITLE
StructureMap unable to recognize h5py package

### ISSUE THREAD

**Issue by jserrano9424** [MannLabs/structuremap#12]
I am trying to run the command `pip install "structuremap[stable]"` on a macOS with an M1 chip, but I am having trouble getting it to recognize the h5py package. I have already updated h5py and tried various troubleshooting methods, but I am still encountering an error. The error message I am receiving is: 

`Copy code 1 error generated. error: command '/usr/bin/clang' failed with exit code 1 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for h5py Failed to build h5py ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects `

I am unable to install the structuremap[stable] package due to this issue with the h5py package.

**Comment by jserrano9424** [comment]
I am trying to run the command `pip install "structuremap[stable]"` on a macOS with an M1 chip, but I am having trouble getting it to recognize the h5py package. I have already updated h5py and tried various troubleshooting methods, but I am still encountering an error. The error message I am receiving is: 

`Copy code 1 error generated. error: command '/usr/bin/clang' failed with exit code 1 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for h5py Failed to build h5py ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects `

I am unable to install the structuremap[stable] package due to this issue with the h5py package.

**Comment by ibludau** [comment]
The stable install appears to create a general issue right now, so this is not macOS M1 specific. I recommend using the loose, normal install (pip install structuremap) for now until this issue is solved.
